name: 'keboola_sample'
version: '1.0.0'
config-version: 2
profile: 'keboola_project'

dispatch:
  - macro_namespace: dbt
    search_order: ['keboola_sample', 'keboola', 'dbt']

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

models:
  keboola_sample:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
